# Generated by Django 2.0.6 on 2018-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1, verbose_name='Article status'),
        ),
    ]
